tap "farion1231/ccswitch"
tap "sunnyyoung/tap"
tap "tw93/tap"
brew "dotbot"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "htop"
brew "hugo"
brew "jenv"
brew "jj"
brew "jq"
brew "jump"
brew "mackup"
brew "mas"
brew "ollama"
brew "pinentry-mac"
brew "tmux"
brew "tree"
brew "zsh"
brew "sunnyyoung/tap/wechattweak"
brew "tw93/tap/mole"
cask "alt-tab"
cask "antigravity"
cask "betterzip"
cask "bruno"
cask "chatgpt"
cask "chatwise"
cask "clash-verge-rev"
cask "claude-code"
cask "codex"
cask "cursor"
cask "font-lora"
cask "font-maple-mono"
cask "font-maple-mono-nf"
cask "font-maple-mono-nf-cn"
cask "fork"
cask "google-chrome"
cask "iina"
cask "jd-gui"
cask "localsend"
cask "memoryanalyzer"
cask "mos"
cask "motrix"
cask "orbstack"
cask "provisionql"
cask "pycharm"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "quicklook-pat"
cask "quicklookase"
cask "raycast"
cask "rectangle"
cask "skim"
cask "squirrel-app"
cask "sublime-text"
cask "syntax-highlight"
cask "telegram-desktop"
cask "vlc"
cask "warp"
cask "webpquicklook"
cask "zulu@17"
cask "zulu@21"
cask "zulu@8"
mas "Amphetamine", id: 937984704
mas "Command X", id: 6448461551
mas "Enpass", id: 732710998
mas "Pie Adblock for Safari", id: 6499055690
mas "Shadowrocket", id: 932747118
mas "The Unarchiver", id: 425424353
mas "WeChat", id: 836500024
mas "WPS Office", id: 1468073139
